gtsam_ex:
  # filePath : "/home/mgkim/catkin_ws/src/gtsamEx/data/sphere.g2o"
  # filePath : "/home/mgkim/catkin_ws/src/gtsamEx/data/parking-garage.g2o"
  # filePath : "/home/mgkim/catkin_ws/src/gtsamEx/data/cubicle.g2o"
  # filePath : "/home/mgkim/catkin_ws/src/gtsamEx/data/rim.g2o"
  # filePath : "/home/mgkim/catkin_ws/src/gtsamEx/data/torus3D.g2o"
  filePath : "/home/mgkim/Desktop/Data-ssd2/01_ITSK_Data/2211231532_ITSK/1670.930879_slam_coordinate.txt"